spring:
  application:
    name: jooq-sample
#Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3309/library
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    initialize: false
    continue-on-error: true
server:
  port: 9001

sample-database:
  url: jdbc:mysql://localhost:3309/library
  username: root
  password: 123456
#jOOQ Configuration
jooq:
  sql:
    dialect: MYSQL





