spring:
  application:
    name: jooq-sample
  aop:
    proxy-target-class: true
#Database Configuration
  datasource:
    druid:
      url: jdbc:mysql://localhost:3309/library
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 123456
      initialize: false
      continue-on-error: true
      aop-patterns: com.brave.jooq.service.*
      WebStatFilter:
        filters: stat
management:
  security:
    enabled: false
server:
  port: 9001

sample-database:
  url: jdbc:mysql://localhost:3309/library
  username: root
  password: 123456
#jOOQ Configuration
jooq:
  sql:
    dialect: MYSQL
liquibase:
  enabled: true
  change-log: classpath:business_table.xml






